pipeline {
    agent {
        kubernetes {
            label 'npm'
            defaultContainer 'npm'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd frontend && npm install && npm run-script build'
            }
        }
    }
}